# Generated by Django 3.2.6 on 2021-10-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0002_remove_product_weight_in_kg'),
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.product'),
        ),
    ]
