# Generated by Django 3.2.6 on 2021-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_remove_orderproductdetails_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
