# Generated by Django 3.2.6 on 2021-12-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_alter_shoppingcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
