# Generated by Django 3.2.6 on 2021-10-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0003_auto_20211019_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitClass',
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
    ]
