# Generated by Django 3.2.6 on 2021-10-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0004_auto_20211020_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_tag_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_tag_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_tag_title',
        ),
    ]
