# Generated by Django 3.2.6 on 2021-10-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0005_auto_20211020_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.PROTECT, to='customAdmin.category'),
        ),
    ]
