# Generated by Django 3.2.6 on 2021-10-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0007_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='status',
            new_name='active',
        ),
    ]
