# Generated by Django 3.2.6 on 2021-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0008_rename_status_coupons_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='E-Shopper', max_length=100)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('paragrapgh', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='./banners/')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
