# Generated by Django 3.2.6 on 2021-10-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0011_alter_product_shipping_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=20),
        ),
    ]
