# Generated by Django 3.2.6 on 2021-10-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0013_alter_attribute_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
