# Generated by Django 3.2.6 on 2021-10-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0014_remove_user_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='paragrapgh',
            new_name='paragraph',
        ),
        migrations.AlterField(
            model_name='banners',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
