# Generated by Django 3.2.6 on 2021-11-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0015_auto_20211023_1818'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
